apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress-cluster-viewer-binder
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - nginx-ingress-cluster-viewer
  resources:
  - clusterroles
  verbs:
  - bind
