apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nsadmin-nginx-extensions
rules:
- apiGroups:
  - k8s.nginx.org
  resources:
  - virtualservers
  - virtualserverroutes
  - transportservers
  - policies
  - virtualservers/status
  - virtualserverroutes/status
  - transportservers/status
  - policies/status
  verbs:
  - list
  - watch
  - get
  - patch
  - create
  - delete
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - list
  - watch
  - get
  - create
  - delete
  - update
